### ISSUE TITLE
集成原 lightgallery.js 的放大缩小按钮能力

### ISSUE THREAD

**Issue by jalr4ever** [halo-sigs/plugin-lightgallery#16]
Hi, 从 https://github.com/sachinchoolur/lightgallery.js 的 README 来看，这个 js 是提供放大缩小按钮的，现在作为插件集成是不提供这个能力么

![image](https://github.com/halo-sigs/plugin-lightgallery/assets/23929139/ea9b65a1-2d40-46e2-82df-cd20341b1769)

**Comment by guqing** [comment]
/kind feature

感谢提出这个问题 🎉
